# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imginfo',
            old_name='mouth',
            new_name='month',
        ),
        migrations.AlterField(
            model_name='imginfo',
            name='discription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imginfo',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
